/*
 * Copyright 2024-2026 NXP
 * NXP Proprietary. This software is owned or controlled by NXP and may only be used
 * strictly in accordance with the applicable license terms. By expressly accepting such terms or by
 * downloading, installing, activating and/or otherwise using the software, you are agreeing that you
 * have read, and that you agree to comply with and are bound by, such license terms. If you do not
 * agree to be bound by the applicable license terms, then you may not retain, install, activate or
 * otherwise use the software.
 */

/*
 * Note:
 * THIS FILE IS AUTO-GENERATED BY TIME SERIES STUDIO. DO NOT MODIFY!
 */

#ifndef _TIMESERIES_H_
#define _TIMESERIES_H_
/* Error status returned functions in the Time Series Studio library */
typedef enum
{
    TSS_SUCCESS                 = 0, /* No error */
    TSS_STATE_ERROR             = 1, /* State is incorrect */
    TSS_BOARD_ERROR             = 2, /* Board information is incorrect */
    TSS_MEMORY_ERROR            = 3, /* Memory error caused by the HEAP Overflow */
    TSS_PREDICT_NOT_ENABLED     = 4, /* Predict function is not enabled */
    TSS_LEARNING_ERROR          = 5, /* Errors occurs during the learning process */
    TSS_LEARNING_NOT_ENOUGH     = 6, /* Not enough calls to learning */
    TSS_RECOMMEND_LEARNING_DONE = 7, /* Reached the recommended calls to learning */
    TSS_NOT_READY               = 8, /* Function is not ready but planed to support */
    TSS_LICENSE_ERROR           = 9, /* Invalid license */
    TSS_UNKNOWN_ERROR           = 10, /* Unknown error */
} tss_status;

typedef enum {
    TASK_AD = 1,
    TASK_AD_ODL = 2,
    TASK_CLS = 3,
    TASK_OC = 4,
    TASK_REG = 5
} task_type_t;

typedef struct {
    unsigned int data_tab;
    unsigned int data_len;
    unsigned int data_dim;
    unsigned int model_size;
    const float *model_addr;
    unsigned int target_num;
    float recommend_threshold;
    const char *lib_id;
    const char *neutron_verion;
    unsigned int recommend_learning_num;
    unsigned char odl_supported;
    unsigned char neutron_enabled;
    unsigned char powerquad_enabled;
} tss_algo_attribute_t;

typedef struct tss_ad_task_ops
{
    /**
     * @brief      Initialize the anomaly detection algorithm.
     * @retval     TSS_SUCCESS              - Initialization succeed.
     */
    tss_status (*init)(void);

    /**
     * @brief      Predict the normal probability of the specified data.
     * @param[in]  data_input               - The data input for the prediction.
     * @param[out] probability              - The predicted probability output.
     * @retval     TSS_SUCCESS              - Prediction succeed.
     * @retval     TSS_PREDICT_NOT_ENABLED  - Model not ready for prediction.
     */
    tss_status (*predict)(const float data_input[], float *probability);
} tss_ad_task_ops_t;

typedef struct tss_ad_odl_task_ops
{
   /**
    * @brief      Initialize the anomaly detection algorithm with the specified model.
    * @param[in]  model_buffer             - The model buffer for initialization, NULL means reset the model.
    * @retval     TSS_SUCCESS              - Initialization succeed.
    */
    tss_status (*init)(const float model_buffer[]);

    /**
     * @brief      Learn new model from the normal data.
     * @param[in]  data_input               - The data input for the learning.
     * @retval     TSS_SUCCESS              - Learning succeed
     * @retval     TSS_LEARNING_NOT_ENOUGH  - More data needed for the learning.
     */
    tss_status (*learn)(const float data_input[]);

    /**
     * @brief      Export the model to the specified buffer.
     * @param[out] model_buffer             - The exported model buffer.
     * @retval     TSS_SUCCESS              - Export succeed.
     * @retval     TSS_PREDICT_NOT_ENABLED  - Model not ready for export.
     */
    tss_status (*export)(float model_buffer[]);

    /**
     * @brief      Predict the normal probability of the specified data.
     * @param[in]  data_input               - The data input for the prediction.
     * @param[out] probability              - The predicted probability output.
     * @retval     TSS_SUCCESS              - Prediction succeed.
     * @retval     TSS_PREDICT_NOT_ENABLED  - Model not ready for prediction.
     */
    tss_status (*predict)(const float data_input[], float *probability);
} tss_ad_odl_task_ops_t;

typedef struct tss_cls_task_ops
{
    /**
     * @brief      Initialize the classification algorithm.
     * @retval     TSS_SUCCESS              - Initialization succeed.
     */
    tss_status (*init)(void);

    /**
     * @brief      Predict the probabilities and class index of the specified data.
     * @param[in]  data_input               - The data input for the prediction.
     * @param[out] probabilities            - The predicted probabilities of all classes
     * @param[out] class_index              - The predicted class index.
     * @retval     TSS_SUCCESS              - Prediction succeed.
     */
    tss_status (*predict)(const float data_input[], float probabilities[], int *class);
} tss_cls_task_ops_t;

typedef struct tss_oc_task_ops
{
    /**
     * @brief      Initialize the one class algorithm.
     * @retval     TSS_SUCCESS              - Initialization succeed.
     */
    tss_status (*init)(void);

    /**
     * @brief      Predict if is outlier and the decision score of the specified data.
     * @param[in]  data_input               - The data input for the prediction.
     * @param[out] is_outlier               - The predicted results of if input is outlier.
     * @param[out] score                    - The predicted score.
     * @retval     TSS_SUCCESS              - Prediction succeed.
     */
    tss_status (*predict)(const float data_input[], float *score, int *is_outlier);
} tss_oc_task_ops_t;

typedef struct tss_reg_task_ops
{
    /**
     * @brief      Initialize the regression algorithm.
     * @retval     TSS_SUCCESS              - Initialization succeed.
     */
    tss_status (*init)(void);

    /**
     * @brief      Predict the targets based on the specified data.
     * @param[in]  data_input               - The data input for the prediction.
     * @param[out] targets                  - The predicted targets output.
     * @retval     TSS_SUCCESS              - Prediction succeed.
     */
    tss_status (*predict)(const float data_input[], float targets[]);

} tss_reg_task_ops_t;

typedef struct tss_task_ops
{
    int task;
    union
    {
        tss_ad_task_ops_t ad_ops;
        tss_ad_odl_task_ops_t ad_odl_ops;
        tss_cls_task_ops_t cls_ops;
        tss_oc_task_ops_t oc_ops;
        tss_reg_task_ops_t reg_ops;
    };
    const tss_algo_attribute_t *(*algo_attribute)(void);

} tss_task_ops_t;

#ifdef __cplusplus
extern "C" {
#endif

extern const tss_task_ops_t *tss_get_task_ops();

#ifdef __cplusplus
}
#endif

#endif /* _TIMESERIES_H_ */